site_name: ASTRA (Auto Stock Trader)
site_author: 후이넘
site_description: 미국 주식 자동매매 프로그램인 ASTRA 매뉴얼 페이지입니다. 
site_url: https://astra-doc.github.io/
theme:
  name: material
  logo: images/astra.ico
  custom_dir: overrides
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.blocks.caption
plugins:
extra:
  analytics:
    provider: google
    property: G-FPPQCT0CKL

nav:
  - 👋 소개: index.md
  - 💻 권장사양: requirements.md
  - 🗃️ 준비하기: prep.md
  - ⚙️ HTS 설정:
    - 🇲 메리츠증권: meritz.md
    - 🇲 메리츠증권 국장: meritz_korea.md
  - 📄 사용방법:
    - ⭐ 공통: usage.md
    - 📈 떨사오팔: tsop.md
    - 📊 시트매매: sheet.md
    - 📈 실시간 떨사오팔: realtime_tsop.md
    - ✨ 자동모드: auto.md
    - ⚙️ 설정: settings.md
    - 🚀 API: api.md
  - 👭 자매품:
    - 📈 실사오팔 백테스트: rtsop_backtest.md
  - ⬇️ 다운로드:
    - ⭐ ASTRA: download.md
    - 📈 실사오팔 백테스트: download_rtsop.md
  - 📌 자주 묻는 질문: faq.md
  - 💬 문의하기: question.md
